### ISSUE TITLE
Should retiring all CIDs be an error?

### ISSUE THREAD

**Issue by dtikhonov** [quicwg/base-drafts#2101]
Retiring all CIDs that have been issued makes the CID issuer unreachable. Should this be a connection error?

It is possible to imagine that the CID issuer may send a new CID to the peer after all its CIDs are retired and then the connection can continue.

Either way, this case should be covered in the draft.

**Comment by marten-seemann** [comment]
I don't think this is the case. An endpoint retires CIDs that it uses as destination CIDs. So if a peer retires all CIDs, it's shooting itself in the foot because it won't be able to send any more packets (until it receives a packet containing a NEW_CONNECTION_ID frame). Therefore, I don't think we need any error condition here.

**Comment by huitema** [comment]
If there was an error, what CID would the node use to send the connection close message?

**Comment by martinthomson** [comment]
You can send CONNECTION_CLOSE, even if you can't accept an ACK, because it's the not peer that has no connection IDs that sends that packet.  Or you can send more NEW_CONNECTION_ID frames.

The only potentially interesting case is that you can't send a packet with a long header, but that's not a problem in this protocol version.

I'm somewhat biased toward silence on this issue.  We encourage the replacement of connection IDs, which works here.  And if an endpoint just made it impossible to keep sending packets, that's a problem that solves itself really.

**Comment by igorlord** [comment]
We can simply disallow RETIRE_CONNECTION_ID to refer to a CID that is being used in a packet containing that RETIRE_CONNECTION_ID frame.  This avoids this very interesting case and ensures that there is a CID to use, if this RETIRE_CONNECTION_ID frame needs to be retransmitted.

**Comment by martinthomson** [comment]
Clever.  But I'm not sure that this relationship is maintained.  We used to have frame processing dependent on the packet header.  It wasn't popular and I think that was the very first thing we fixed.

**Comment by igorlord** [comment]
Frame processing dependent on the packet header is a requirement on the receiver.  Error detection by the receiver is not a MUST here.  A prohibition against RETIRE_CONNECTION_ID CID used by send RETIRE_CONNECTION_ID would be MUST for the sender.

(If we do not resolve this in the Transport draft, this would certainly need to make its way into Applicability draft as a warning against retiring all CIDs.)

**Comment by janaiyengar** [comment]
I'm with @martinthomson on this one. There are many ways in which an endpoint can shoot itself in the foot, and this is one more.  I'll note that the onus here really is on the peer issuing CIDs.  Retiring is fine if it's the only one that the peer has issued, and it needs to be retired because of a change in the peer's address for example. A peer that doesn't issue new ones ahead of time is responsible.

That said, an endpoint that retires CIDs willy-nilly is simply hurting itself. I wouldn't be opposed to having something in the applicability draft, along with text for when something should be retired.

**Comment by marten-seemann** [comment]
That doesn’t solve the issue. You can use two connection IDs and retire CID A in B and CID B in A.

**Comment by dtikhonov** [comment]
This true.  I thought the consensus was to prohibit retiring all connection IDs, @martinthomson?

**Comment by MikeBishop** [comment]
Consensus was to prohibit retiring the CID used in the packet which contains it.  The intent is that RETIRE means "I have ceased using this CID," so the cross-retiring is technically possible but still against the intent.

**Comment by ianswett** [comment]
My understanding is that CIDs must be used in order.  Given that, if you retire CID A in a packet with CID B then you can't then send CID A in a subsequent packet.  And vice versa, so I think we're ok assuming CIDs must be used in order.

**Comment by dtikhonov** [comment]
OK, sounds good.  I will make a PR to that effect.

**Comment by marten-seemann** [comment]
> My understanding is that CIDs must be used in order. Given that, if you retire CID A in a packet with CID B then you can't then send CID A in a subsequent packet. And vice versa, so I think we're ok assuming CIDs must be used in order.

@ianswett I don't think we have that requirement. You're allowed to use multiple CIDs at the same time. Or did I miss any text in the spec?

**Comment by martinthomson** [comment]
Apparently "fixes issue #foo" isn't equivalent to "fixes #foo".  That's a little annoying, if not entirely surprising.

**Comment by mnot** [comment]
From Tokyo:

> MUST not do it, may generate error. (retry on the next path)
